"""add server_default to users.is_active

Revision ID: 1b2fa9cd020e
Revises: f579dd7cf7a4
Create Date: 2026-02-26 20:13:35.223653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '1b2fa9cd020e'
down_revision: Union[str, Sequence[str], None] = 'f579dd7cf7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_active",
        server_default=text("true"),
        existing_type=sa.Boolean(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_active",
        server_default=None,
        existing_type=sa.Boolean(),
    )
    # ### end Alembic commands ###
