"""add constraints at habit_logs and change created_at to DB server default

Revision ID: f579dd7cf7a4
Revises: 9fbf7f669531
Create Date: 2026-02-25 17:40:23.018861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f579dd7cf7a4'
down_revision: Union[str, Sequence[str], None] = '9fbf7f669531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_user_habit_log_date', 'habit_logs', ['user_id', 'habit_id', 'log_date'])
    op.drop_constraint(op.f('habit_logs_habit_id_fkey'), 'habit_logs', type_='foreignkey')
    op.create_foreign_key('habit_logs_habit_id_fkey', 'habit_logs', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('habit_logs_habit_id_fkey', 'habit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('habit_logs_habit_id_fkey'), 'habit_logs', 'habits', ['habit_id'], ['id'])
    op.drop_constraint('uniq_user_habit_log_date', 'habit_logs', type_='unique')
    # ### end Alembic commands ###
